Map<Character, Integer> romanNumerals = new HashMap<>();
        romanNumerals.put('I', 1);
        romanNumerals.put('V', 5);
        romanNumerals.put('X', 10);
        romanNumerals.put('L', 50);
        romanNumerals.put('C', 100);
        romanNumerals.put('D', 500);
        romanNumerals.put('M', 1000);

        int result = 0;

        for (int i = 0; i < s.length(); i++) {
            int currentSymbolValue = romanNumerals.get(s.charAt(i));

            // Check if it's the last symbol or the current symbol's value is greater than or equal to the next symbol's value
            if (i == s.length() - 1 || romanNumerals.get(s.charAt(i + 1)) <= currentSymbolValue) {
                result += currentSymbolValue;
            } else {
                // If true, subtract the current symbol's value from the result
                result -= currentSymbolValue;
            }
        }

        return result;
    }
